server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: app
  pipeline_stages:
  - match:
      selector: '{author="usr1"}'
      stages:
      - json:
          expressions:
            level: level
            time: timestamp
      - timestamp:
          source: time
          format: RFC3339Nano
      - drop:
          older_than: 168h # 7 days in hours
  - match:
      selector: '{author="usr2"}'
      stages:
      - regex:
          expression: '.*"@timestamp":"(?P<time>[T\d-:.Z]*)"'
      - timestamp:
          source: time
          format: RFC3339Nano
      - drop:
          older_than: 168h # 7 days in hours
  static_configs:
  - targets:
      - localhost
    labels:
      author: usr1
      __path__: /var/log/usr1/*log
  - targets:
      - localhost
    labels:
      author: usr2
      __path__: /var/log/usr2/*log

# Ref: https://grafana.com/docs/loki/latest/clients/promtail/