server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: app
  pipeline_stages:
    - json:
        expressions:
          level: level
          time: timestamp
    - timestamp:
        source: time
        format: RFC3339Nano
    - drop:
        older_than: 168h # 7 days in hours
  static_configs:
  - targets:
      - localhost
    labels:
      author: wayne
      __path__: /var/log/wayne/*log
  - targets:
      - localhost
    labels:
      author: frank
      __path__: /var/log/frank/*log
